spring:
  profiles:
    active: dev

  datasource:
    url: IT'S A FAKE ONE, PLEASE REPLACE IT WITH YOUR OWN
    username: IT'S A FAKE ONE, PLEASE REPLACE IT WITH YOUR OWN
    password: IT'S A FAKE ONE, PLEASE REPLACE IT WITH YOUR OWN

  application:
    name: finance-portfolio-backend

server:
  port: 8080
  servlet:
    context-path: /finance-portfolio

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html

ai:
  ollama:
    base-url: http://localhost:11434
    model-name: llama3.2

logging:
  level:
    dev.langchain4j: DEBUG